### PR TITLE
srp/create prescription

### PR DESCRIPTION
**Pull request by SammyRobensParadise**
Adding pagination to patients page  and patients page in general

### CODE REVIEW

**Review by hnagri52 — COMMENTED** [review]
I think we should return all patients by location for staff account

**Comment by SammyRobensParadise** [comment]
> I think we should return all patients by location for staff account

patients have no association with a specific location. This is because patients can visit multiple locations, i.e part of the "platform" approach

**Comment by hnagri52** [comment]
> > I think we should return all patients by location for staff account
> 
> patients have no association with a specific location. This is because patients can visit multiple locations, i.e part of the "platform" approach



> > I think we should return all patients by location for staff account
> 
> patients have no association with a specific location. This is because patients can visit multiple locations, i.e part of the "platform" approach

I agree, not all patients have a specific location, but I do think staff members at different locations should only be able to see patient information at their respective location.

**Comment by SammyRobensParadise** [comment]
> > > I think we should return all patients by location for staff account
> > 
> > 
> > patients have no association with a specific location. This is because patients can visit multiple locations, i.e part of the "platform" approach
> 
> > > I think we should return all patients by location for staff account
> > 
> > 
> > patients have no association with a specific location. This is because patients can visit multiple locations, i.e part of the "platform" approach
> 
> I agree, not all patients have a specific location, but I do think staff members at different locations should only be able to see patient information at their respective location.

I think that is a valid security measure. we can require patients to "register" at a specific location via the application? perhaps this is a post-lfp feature. what are your thoughts @rajwanialiya @JJwilkin ?

**Comment by SammyRobensParadise** [comment]
> > > > I think we should return all patients by location for staff account
> > > 
> > > 
> > > patients have no association with a specific location. This is because patients can visit multiple locations, i.e part of the "platform" approach
> > 
> > 
> > > > I think we should return all patients by location for staff account
> > > 
> > > 
> > > patients have no association with a specific location. This is because patients can visit multiple locations, i.e part of the "platform" approach
> > 
> > 
> > I agree, not all patients have a specific location, but I do think staff members at different locations should only be able to see patient information at their respective location.
> 
> I think that is a valid security measure. we can require patients to "register" at a specific location via the application? perhaps this is a post-lfp feature. what are your thoughts @rajwanialiya @JJwilkin ?

there is an additional trade-off as well, because it becomes less of a "plug-and-play" model for patients because they need to keep track of what pharmacy locations they are at, and what locations they aren't. it also introduces the issue of timing. how long can a patient not visit a pharmacy before we remove their information from that location?

**Comment by SammyRobensParadise** [comment]
I have setup the search using offset pagination to start, but we can easily switch to cursor https://www.prisma.io/docs/concepts/components/prisma-client/pagination which would be advantageous for scaling. it is a very easy switch but would require some massaging

**Review by JJwilkin — APPROVED** [review]

**Pull request merged**
